# Generated by Django 5.1.1 on 2024-10-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0002_blogpost_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
