# Generated by Django 5.1.1 on 2024-10-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0003_remove_libro_autor_delete_autor_delete_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
