# Generated by Django 5.1.1 on 2024-10-13 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0004_remove_blogpost_author_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='noticias_blogposts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
