# Generated by Django 5.1.1 on 2024-10-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0006_blogpost_alter_comment_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Categoria',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
