# Generated by Django 5.1.1 on 2024-10-17 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0008_alter_blogpost_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Categoria',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.CASCADE, to='Noticias.categoria'),
        ),
    ]
